/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FlightInsuranceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "airline"
      | "buyInsurance"
      | "depositEscrow"
      | "payoutAmount"
      | "policies"
      | "reportDelay"
      | "thresholdHours"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowDeposited"
      | "InsurancePurchased"
      | "PayoutExecuted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "airline", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyInsurance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositEscrow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payoutAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "policies", values: [string]): string;
  encodeFunctionData(
    functionFragment: "reportDelay",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "thresholdHours",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "airline", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyInsurance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payoutAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "thresholdHours",
    data: BytesLike
  ): Result;
}

export namespace EscrowDepositedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InsurancePurchasedEvent {
  export type InputTuple = [flightNumber: string, passenger: AddressLike];
  export type OutputTuple = [flightNumber: string, passenger: string];
  export interface OutputObject {
    flightNumber: string;
    passenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutExecutedEvent {
  export type InputTuple = [
    flightNumber: string,
    passenger: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    flightNumber: string,
    passenger: string,
    amount: bigint
  ];
  export interface OutputObject {
    flightNumber: string;
    passenger: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlightInsurance extends BaseContract {
  connect(runner?: ContractRunner | null): FlightInsurance;
  waitForDeployment(): Promise<this>;

  interface: FlightInsuranceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  airline: TypedContractMethod<[], [string], "view">;

  buyInsurance: TypedContractMethod<
    [flightNumber: string],
    [void],
    "nonpayable"
  >;

  depositEscrow: TypedContractMethod<[], [void], "payable">;

  payoutAmount: TypedContractMethod<[], [bigint], "view">;

  policies: TypedContractMethod<
    [arg0: string],
    [
      [string, boolean, boolean] & {
        passenger: string;
        isActive: boolean;
        isSettled: boolean;
      }
    ],
    "view"
  >;

  reportDelay: TypedContractMethod<
    [flightNumber: string, delayHours: BigNumberish],
    [void],
    "nonpayable"
  >;

  thresholdHours: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "airline"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "buyInsurance"
  ): TypedContractMethod<[flightNumber: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositEscrow"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "payoutAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, boolean, boolean] & {
        passenger: string;
        isActive: boolean;
        isSettled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "reportDelay"
  ): TypedContractMethod<
    [flightNumber: string, delayHours: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "thresholdHours"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EscrowDeposited"
  ): TypedContractEvent<
    EscrowDepositedEvent.InputTuple,
    EscrowDepositedEvent.OutputTuple,
    EscrowDepositedEvent.OutputObject
  >;
  getEvent(
    key: "InsurancePurchased"
  ): TypedContractEvent<
    InsurancePurchasedEvent.InputTuple,
    InsurancePurchasedEvent.OutputTuple,
    InsurancePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "PayoutExecuted"
  ): TypedContractEvent<
    PayoutExecutedEvent.InputTuple,
    PayoutExecutedEvent.OutputTuple,
    PayoutExecutedEvent.OutputObject
  >;

  filters: {
    "EscrowDeposited(uint256)": TypedContractEvent<
      EscrowDepositedEvent.InputTuple,
      EscrowDepositedEvent.OutputTuple,
      EscrowDepositedEvent.OutputObject
    >;
    EscrowDeposited: TypedContractEvent<
      EscrowDepositedEvent.InputTuple,
      EscrowDepositedEvent.OutputTuple,
      EscrowDepositedEvent.OutputObject
    >;

    "InsurancePurchased(string,address)": TypedContractEvent<
      InsurancePurchasedEvent.InputTuple,
      InsurancePurchasedEvent.OutputTuple,
      InsurancePurchasedEvent.OutputObject
    >;
    InsurancePurchased: TypedContractEvent<
      InsurancePurchasedEvent.InputTuple,
      InsurancePurchasedEvent.OutputTuple,
      InsurancePurchasedEvent.OutputObject
    >;

    "PayoutExecuted(string,address,uint256)": TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;
    PayoutExecuted: TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;
  };
}
