/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FlightInsurance } from "./FlightInsurance";
export * as factories from "./factories";
export { FlightInsurance__factory } from "./factories/FlightInsurance__factory";
